#!/usr/bin/env bash

(($# < 2)) && echo "Missing parameters" && exit 1

dest=$1; shift
case "$dest" in
    osx)
        exec bash create_bundle.osx "$@"
        break;;
    ios)
        exec bash create_bundle.ios "$@"
        break;;
    win*)
        exec bash create_bundle.win "$@"
        break;;
    *)
        exit 1;
        break;;
esac
