#!/usr/bin/env bash

(($# < 2)) && echo "Missing parameters" && exit 1

dest=$1; shift
case "$dest" in
    osx)
        exec bash create_bundle.osx "$@"
        break;;
    ios)
        exec bash create_bundle.ios "$@"
        break;;
    android)
        exec bash create_bundle.android "$@"
        break;;
    win*)
        exec bash create_bundle.win "$@"
        break;;

    lin*)
        exec bash create_bundle.lin "$@"
        break;;
    *)
        echo "Unknown bundle target: $@"
        exit 1;
        break;;
esac
