#!/usr/bin/env bash

(($# < 2)) && echo "Missing parameters" && exit 1

SYSTEM=$1
#if SYSTEM == osx...

TARGET=$2
APP_NAME=${3:-$TARGET}
TARGET_APP="$APP_NAME".app
CONFIG=${4:-Release}

mkdir -p "build/${CONFIG}/${TARGET_APP}/Contents/"{MacOS,Resources}

INFO=
RFMT=
ICON=
if [[ -f "sources/Info.plist" ]]
then
    INFO="sources/Info.plist"
    cp "$INFO" "build/${CONFIG}/${TARGET_APP}/Contents/"
else
    INFO="build/${CONFIG}/${TARGET_APP}/Contents/Info.plist"
    cp templates/Info.plist.tmpl "$INFO"
    sed -i "s,%TARGET%,${TARGET},g" "$INFO"
    sed -i "s,%APP_NAME%,${APP_NAME},g" "$INFO"
fi
if [[ -f "sources/RecentFilesMenuTemplate.nib" ]]
then
    RFMT="sources/RecentFilesMenuTemplate.nib"
    cp "$RFMT" "build/${CONFIG}/${TARGET_APP}/Contents/Resources/"
else
    RFMT="build/${CONFIG}/${TARGET_APP}/Contents/Resources/RecentFilesMenuTemplate.nib"
    cp "templates/RecentFilesMenuTemplate.nib" "$RFMT"
fi
if [[ -f "sources/Icon.icns" ]]
then
    ICON="sources/Icon.icns"
    cp "$ICON" "build/${CONFIG}/${TARGET_APP}/Contents/Resources/"
else
    ICON="build/${CONFIG}/${TARGET_APP}/Contents/Resources/Icon.icns"
    cp "templates/RecentFilesMenuTemplate.nib" "$ICON"
fi

echo 'APPL????' > build/${CONFIG}/${TARGET_APP}/Contents/PkgInfo
cp "$TARGET" build/${CONFIG}/${TARGET_APP}/Contents/MacOS/
